# Generated by Django 4.1 on 2022-08-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0002_alter_familiar_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
