# Generated by Django 4.1 on 2022-09-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='user_create',
        ),
    ]
