# Generated by Django 4.1 on 2022-09-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(null=True, upload_to='productos/')),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('fecha_Fabric', models.DateTimeField(auto_now_add=True)),
                ('km', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
