# Generated by Django 4.1 on 2022-09-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0002_auto_delete_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='fecha_Fabric',
        ),
        migrations.AddField(
            model_name='auto',
            name='anio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
