# Generated by Django 4.1 on 2022-09-29 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppEcommerce', '0002_remove_auto_user_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='user_create',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_create', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
