# Generated by Django 4.1 on 2022-09-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0004_color_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.color'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='autos/'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.marca'),
        ),
    ]
