# Generated by Django 4.1 on 2022-10-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0005_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='user',
        ),
    ]
