# Generated by Django 4.1 on 2022-10-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0007_auto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='Descripcion',
            field=models.TextField(default=''),
        ),
    ]
