# Generated by Django 4.1 on 2022-10-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0008_auto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='Descripcion',
            new_name='descripcion',
        ),
    ]
