# Generated by Django 4.1 on 2022-09-26 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha_envio',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 21, 13, 49, 149766)),
        ),
    ]
