# Generated by Django 4.1 on 2022-10-09 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajeria', '0002_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
