# Generated by Django 4.1 on 2022-10-07 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajeria', '0012_alter_mensajes_fecha_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha_envio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
