# Generated by Django 4.1 on 2022-10-07 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajeria', '0013_alter_mensajes_fecha_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha_envio',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 10, 31, 58, 868220)),
        ),
    ]
