# Generated by Django 4.1 on 2022-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajeria', '0014_alter_mensajes_fecha_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha_envio',
            field=models.DateField(default='Fri Oct  7 10:34:41 2022'),
        ),
    ]
